version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.0
    - 1.4.1
    - 1.4.10
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
  - dependency-name: aiogram
    versions:
    - "2.12"
    - 2.12.1
  - dependency-name: databases
    versions:
    - 0.4.2
  - dependency-name: alembic
    versions:
    - 1.5.6
    - 1.5.7
